#cloud-config
package_update: true
package_upgrade: true

packages:
  - git
  - curl
  - apt-transport-https
  - ca-certificates
  - software-properties-common

runcmd:
  - curl -fsSL https://get.docker.com -o get-docker.sh
  - sh get-docker.sh

  - usermod -aG docker azureuser

  - systemctl enable docker
  - systemctl start docker

  - git clone https://github.com/taraskibysh/open-data-ai-analytics.git /opt/app

  - cd /opt/app
  - docker compose up -d

  - cd /opt/app/monitoring
  - docker compose -f docker-compose.monitoring.yml up -d