apiVersion: apps/v1
kind: Deployment
metadata:
  name: docflow-web
  namespace: docflow-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: docflow-web
  template:
    metadata:
      labels:
        app: docflow-web
    spec:
      containers:
      - name: web
        image: taraskibysh06/docflow-web:v1
        ports:
        - containerPort: 8866
        volumeMounts:
        - name: reports-volume
          mountPath: /shared/reports
        - name: plots-volume
          mountPath: /shared/plots
      volumes:
      - name: reports-volume
        hostPath:
          path: /opt/app/reports
          type: DirectoryOrCreate
      - name: plots-volume
        hostPath:
          path: /opt/app/plots
          type: DirectoryOrCreate
