name: CI (Self-Hosted Runner)

on:
  workflow_dispatch:

jobs:
  run-local-visualization:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup environment, Run Analysis and Visualization
        run: |
          echo "=== setup virtual environment ==="
          python -m venv venv
          source venv/bin/activate
          
          python -m pip install --upgrade pip
          pip install jupyter nbconvert ipykernel requests pandas openpyxl scikit-learn matplotlib seaborn
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
          python src/data_loader.py
          
          jupyter nbconvert --to notebook --execute --inplace notebooks/data_research.ipynb
          
          mkdir -p artifacts/visualization
          jupyter nbconvert --to html --execute notebooks/visualization.ipynb --output-dir artifacts/visualization/

      - name: Upload local artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: selfhosted-visualization-result
          path: artifacts/visualization/*.html